# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{googleajax}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["geemus(Wesley Beary)", "Marc-Andre Lafortune"]
  s.date = %q{2010-02-26}
  s.email = %q{me@geemus.com}
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "README.txt",
     "Rakefile",
     "VERSION",
     "googleajax.gemspec",
     "lib/googleajax.rb",
     "lib/googleajax/api.rb",
     "lib/googleajax/as_hash.rb",
     "lib/googleajax/as_open_struct.rb",
     "lib/googleajax/base.rb",
     "lib/googleajax/basic.rb",
     "lib/googleajax/extensions/hash.rb",
     "lib/googleajax/extensions/kernel.rb",
     "lib/googleajax/extensions/string.rb",
     "lib/googleajax/feed.rb",
     "lib/googleajax/filters.rb",
     "lib/googleajax/hash.rb",
     "lib/googleajax/language.rb",
     "lib/googleajax/request.rb",
     "lib/googleajax/results.rb",
     "lib/googleajax/search.rb",
     "spec/googleajax_as_open_struct_spec.rb",
     "spec/googleajax_basic_spec.rb",
     "spec/googleajax_common.rb",
     "spec/googleajax_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/geemus/googleajax}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby wrapper to the Google AJAX API REST interfaces(Feeds, Language and Search).}
  s.test_files = [
    "spec/googleajax_as_open_struct_spec.rb",
     "spec/googleajax_basic_spec.rb",
     "spec/googleajax_common.rb",
     "spec/googleajax_spec.rb",
     "spec/spec_helper.rb",
     "spec/temp_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<json>, [">= 1.0.0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<json>, [">= 1.0.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<json>, [">= 1.0.0"])
  end
end

